// AUTO-GENERATED by flutter_rust_bridge_codegen.
// DO NOT EDIT MANUALLY.
//
// Run `flutter_rust_bridge_codegen generate` from `bindings/flutter/`
// to regenerate this file after changing `api.rs`.
//
// This stub allows the crate to compile before codegen has been run.
// After running codegen, this file will be replaced with the full generated bridge.

#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]

// The real generated content is produced by:
//   flutter_rust_bridge_codegen generate
// See: https://cjycode.com/flutter_rust_bridge/
