// flutter_rust_bridge entry point.
// The `api` module contains all functions annotated with #[frb] that are
// exposed to Dart. The codegen tool reads this file to generate the Dart side.

pub mod api;
pub mod runtime;
pub mod frb_generated; // generated by flutter_rust_bridge_codegen — do not edit manually
