// AUTO-GENERATED by flutter_rust_bridge_codegen.
// DO NOT EDIT MANUALLY.
//
// Run `flutter_rust_bridge_codegen generate` from `bindings/flutter/`
// to regenerate this file after changing `rust/src/api.rs`.
//
// This stub allows the Dart package to compile before codegen has been run.
// After running codegen, this file will be replaced with the full generated bridge.

// ignore_for_file: unused_import, unused_element, dead_code

import 'dart:async';
import 'dart:convert';

// ---------------------------------------------------------------------------
// Stub implementations — replaced by codegen output
// ---------------------------------------------------------------------------

/// Initialize the EdgeChain runtime.
Future<void> edgeInit({String? dbPath}) async {
  // Implemented via FFI after codegen. Stub for now.
}

/// Returns true if the runtime has been initialized.
bool edgeIsInitialized() => false;

/// Register a named agent.
void edgeRegisterAgent({
  required String id,
  required String systemPrompt,
  int maxSteps = 10,
  List<String>? allowedCommands,
}) {}

/// Run an agent and return the result.
Future<EdgeAgentResult> edgeAgentRun({
  required String agentId,
  required String userInput,
}) async {
  return EdgeAgentResult(
    text: '[Bridge not yet generated] $userInput',
    steps: [],
    citations: [],
    totalTokens: 0,
  );
}

/// Register a command (Dart-side handler).
void edgeRegisterCommand({
  required String name,
  required String description,
  String category = 'read_only',
  String inputSchemaJson = '{}',
}) {}

/// Set the Dart handler for a registered command.
void edgeSetCommandHandler({
  required String name,
  required String Function(String argsJson) handler,
}) {}

/// Store a value in memory.
Future<void> edgeMemorySet({required String key, required String valueJson}) async {}

/// Retrieve a value from memory.
Future<EdgeMemoryEntry?> edgeMemoryGet({required String key}) async => null;

/// Delete a key from memory.
Future<void> edgeMemoryDelete({required String key}) async {}

/// List memory keys.
Future<List<String>> edgeMemoryListKeys({String? prefix}) async => [];

// ---------------------------------------------------------------------------
// Data classes (mirrors Rust structs in api.rs)
// ---------------------------------------------------------------------------

class EdgeAgentResult {
  final String text;
  final List<EdgeAgentStep> steps;
  final List<EdgeCitation> citations;
  final int totalTokens;

  const EdgeAgentResult({
    required this.text,
    required this.steps,
    required this.citations,
    required this.totalTokens,
  });
}

class EdgeAgentStep {
  final int step;
  final String actionType;
  final String observation;

  const EdgeAgentStep({
    required this.step,
    required this.actionType,
    required this.observation,
  });
}

class EdgeCitation {
  final String sourceId;
  final String excerpt;

  const EdgeCitation({required this.sourceId, required this.excerpt});
}

class EdgeMemoryEntry {
  final String id;
  final String key;
  final String valueJson;
  final List<String> tags;

  const EdgeMemoryEntry({
    required this.id,
    required this.key,
    required this.valueJson,
    required this.tags,
  });

  dynamic get value => jsonDecode(valueJson);
}
