name: flutter_notes_assistant
description: EdgeChain Flutter Notes Assistant example app.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  edgechain_flutter:
    path: ../../bindings/flutter
